export enum BooksActions {
	BOOKS_SEARCH_ACTION = 'BOOKS_SEARCH_ACTION',
	BOOKS_REQUEST_ACTION = 'BOOKS_REQUEST_ACTION',
	BOOKS_SUCCESS_ACTION = 'BOOKS_SUCCESS_ACTION',
	BOOKS_FAILURE_ACTION = 'BOOKS_FAILURE_ACTION',

	LOAD_MORE_ACTION = 'LOAD_MORE_ACTION',
	LOAD_MORE_REQUEST_ACTION = 'LOAD_MORE_REQUEST_ACTION',
	LOAD_MORE_SUCCESS_ACTION = 'LOAD_MORE_SUCCESS_ACTION',
	LOAD_MORE_FAILURE_ACTION = 'LOAD_MORE_FAILURE_ACTION',
}
